BookaSpeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

registerPembicara/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "register"

urlpatterns = [
    path('', views.register, name="form"),
    path('confirm', views.confirm, name="confirm"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="search"

urlpatterns = [
    path('', views.search, name="search"),
    path('<category>/', views.search_bycategory, name="byCategory"),
    path('', views.search_bynama, name="byName"),
    path('', views.search_all, name="searchAll")
]

speaker_profile/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'speaker_profile'

urlpatterns = [
    path('<id>', views.profile, name='profile'),
    path('<id>/check_availability/', views.check_availability, name='check_availability'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speakerapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"

urlpatterns = [
    path('', index, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speakerapp/models.py
from django.db import models

speakerapp/forms.py
from django import forms
from . import models
from registerPembicara.models import Pembicara

speakerapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponse
from registerPembicara import forms, models
# from .forms import searchForm

def index(request):
    form = forms.RegisterForm()
    pembicaras = models.Pembicara.objects.all().order_by('-counter')[0:3]
    pemb = {
        'pembicara_data' : pembicaras,
    }
    return render(request, "index.html", pemb)

# def filtersearch(request):
#     filterKota = request.GET
#     print(filterKota)
#     filter = models.Pembicara.objects.filter(city = filterKota)
#     arg={
#         'filter':filter
#         }

#     return render(request,'filter.html',arg)

speakerapp/templates/index.html
{% extends 'base.html' %}

    {% block content %}
        <a href="#home" target="_self">
            <div class="button_up position-fixed">
                <i class="fas fa-angle-double-up"></i>
            </div>
        </a>
        <div id= "home" class="texthome container-fluid">
          <div class="txtcol col container">
            <div class="texthome2 row">
              BookaSpeaker
            </div>
            <div class="texthome3 row">
                is a platform to connect speakers and clients around Indonesia.
            </div>
            <div class="texthome3 row" style="padding-top: 9%;">
                Lets us know you’re a good speaker
            </div>
            <a class="btnhome btn btn-primary" href="{% url 'register:form' %}" role="button">Join as Speaker</a>

          </div>
        </div>
        <div class="text2 container-fluid">
          <div class="topspeak container-fluid">
            Top Speakers of The Week
          </div>
          <div class="row" style="padding: 5%; margin-right: 0;">
                {% csrf_token %}
                {% for pembicara in pembicara_data %}
            <div class="col ">
                <div class="topspeak2 container">
                        {% if pembicara.photo %}
                        <img src={{pembicara.photo.url}} class="img-fluid imgtop" alt="Responsive image">
                        {% endif %}
                    <div class="container-fluid speaknama">
                        {{ pembicara.first_name }} </br> {{ pembicara.last_name }} 
                    </div>
                    <div class="container-fluid speaknama speakjabatan">
                            {{ pembicara.position }}
                    </div>
          
                    <div class="container-fluid " style="width: 100%;">
                        <div class="container speaknama speakkategori">
                                {{ pembicara.category }}
                        </div>
                    </div>
                    <div class="container-fluid speaknama speakket">
                        <i class="fas fa-map-marker-alt"></i>  {{ pembicara.city }} </br>
                        <i class="fas fa-tags"></i> Rp {{ pembicara.fee }}
                    </div>
                    <div class="container-fluid speaknama">
                        <a href="{% url 'speaker_profile:profile' id=pembicara.id %}">See More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
          </div>
          <div class="row" style="margin-right: 0;">
              <a class="btnspeak btn btn-primary" href="{% url 'search:searchAll' %}" role="button">More Speakers</a>
          </div>
        </div>
        <div class="txtcopy container-fluid">
            Copyright © 2019 BookaSpeaker
        </div>
    {% endblock %}