BookaSpeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

registerPembicara/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "register"

urlpatterns = [
    path('', views.register, name="form"),
    path('confirm', views.confirm, name="confirm"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="search"

urlpatterns = [
    path('', views.search, name="search"),
    path('<category>/', views.search_bycategory, name="byCategory"),
    path('', views.search_bynama, name="byName"),
    path('', views.search_all, name="searchAll")
]

speakerapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"

urlpatterns = [
    path('', index, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Raleway:400,700&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" />
        <title>BookaSpeaker</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <link rel="stylesheet" href="{% static 'register.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'style_profile.css' %}">
        <script src="https://kit.fontawesome.com/4b60c8a34d.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
    </head>
    <body>
        <nav id = "navbar" class="navbar navbar-expand-lg navbar-light position-sticky fixed-top">
            <a class= "logo" href="{% url 'homepage:home'%}">
                <img src="{% static 'logo.png' %}">
            </a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="btn-group">
                    <button type="button" class="category-search btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Category
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'search:byCategory' category='IT' %}">IT</a>
                        <a class="dropdown-item" href="{% url 'search:byCategory' category='Entertainment' %}">Entertainment</a>
                        <a class="dropdown-item" href="{% url 'search:byCategory' category='Beauty' %}">Beauty</a>
                        <a class="dropdown-item" href="{% url 'search:byCategory' category='Business' %}">Business</a>
                    </div>
                </div>
                <!-- <form action="{% url 'search:byName' %}" method="GET">
                    <div class="input-group">
                        <input type="text" placeholder="Search by name or city" aria-describedby="button-addon6" class="form-control" name="cari">
                        <div class="input-group-append">
                            <button id="button-addon6" type="submit" class="btn btn-info"><i class="fa fa-search"></i></button>
                        </div>
                    </div> 
                </form> -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'homepage:home'%}">Home</a>
                    </li>
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'search:searchAll' %}">Speakers</a>
                    </li>
                    <li class="nav-item ml auto">
                        <a class="nav-link" href="{% url 'register:form' %}">Register</a>
                    </li>
                </ul>
            </div>
        </nav>  
        {% block content %}
        {% endblock %}
    </body>
</html>