BookaSpeakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('speakerapp.urls')),
    path('search/', include('searchapp.urls')),
    path('profile/', include('speaker_profile.urls')),
    path('register/', include('registerPembicara.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

 

searchapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="search"

urlpatterns = [
    path('', views.search, name="search"),
    path('<category>/', views.search_bycategory, name="byCategory"),
    path('', views.search_bynama, name="byName"),
    path('', views.search_all, name="searchAll")
]

speaker_profile/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'speaker_profile'

urlpatterns = [
    path('<id>', views.profile, name='profile'),
    path('<id>/check_availability/', views.check_availability, name='check_availability'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

searchapp/models.py
from django.db import models

# Create your models here.

searchapp/views.py
from django.shortcuts import render
from registerPembicara.models import Pembicara

# Create your views here.
def search(request):
    data = Pembicara.objects.all()
    if request.method == "GET":
        status = request.GET.get("search")
        if status == "Descending":
            data = Pembicara.objects.all().order_by("-fee")
        else:
            data = Pembicara.objects.all().order_by("fee")

    return render(request, "search.html", {
        "data_pembicara" : data,
    })

def search_all(request):
    data= Pembicara.objects.all()
    return render(request, 'search.html', {'data_pembicara':data})

def search_bycategory(request, category):
    if request.method == "GET":
        category = Pembicara.objects.all().filter(category = category)
    return render(request, "search.html", {"data_pembicara":category})

def search_bynama(request):
    value = request.GET.get('cari')   
    print(value) 
    firstname = Pembicara.objects.filter(first_name__icontains=value)
    lastname = Pembicara.objects.filter(last_name__icontains=value)
    kota = Pembicara.objects.filter(city__icontains=value)
    hasil = firstname | lastname | kota
    return render(request, "search.html", {"data_pembicara":firstname, "value":value})

searchapp/templates/search.html
{% extends 'base.html' %}
    {% block content %}
    <div class="speaker">
        <div class="speaker-text">
            Speakers
        </div>
    </div>

    <div class="container">
        <form class="container-sort" action="{% url 'search:search' %}" method="GET">
            <select name="search">
                <option selected="selected" disabled>Sort by :</option>
                <option value="Descending">Fee (Highest to Lowest)</option>
                <option value="Ascending">Fee (Lowest to Highest)</option>
            </select>
            <input type="submit" value="Sort" />
        </form>
        <div class="container-pembicara">
            {% for pembicara in data_pembicara %}
            <div class="card-pembicara">
                <div class="foto-pembicara">
                    <img src={{pembicara.photo.url}} class="img-fluid imgtop" alt="Responsive image">
                </div>
                <div class="primary">
                    {{pembicara.first_name}} </br> {{pembicara.last_name}}
                </div>
                <div class="primary jabatan-pembicara">
                    {{pembicara.position}}
                </div>
                <div class="container-kategori">
                    <div class="primary kategori-pembicara">
                        {{pembicara.category}}
                    </div>
                </div>
                <div class="primary ket-pembicara">
                    <i class="fas fa-map-marker-alt"></i> {{pembicara.city}} </br>
                    <i class="fas fa-tags"></i> Rp {{pembicara.fee}}
                </div>
                <div class="primary">
                    <a href="{% url 'speaker_profile:profile' id=pembicara.id %}">See More</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="txtcopy container-fluid">
        Copyright © 2019 BookaSpeaker
    </div>
{% endblock %}